TajSanchay/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('installments/', include('installment.urls')),
    path('profile', views.profile, name='profile'),
    path('loan/', include('loan.urls')),
    path('reference/', include('reference.urls')),
    path('savings/', include('savings.urls')),
    # path('loans/', views.loan_listing.as_view()),
]

loan/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add', views.add, name='loan_add'),
    path('list', views.list, name='loan_list'),
    path('profile/<int:id>', views.profile, name='loan_profile'),
]

reference/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add', views.add, name='reference_add'),
    path('list', views.list, name='reference_list'),
    path('profile/<int:id>', views.profile, name='reference_profile'),
]

loan/models.py
from django.db import models
from reference.models import Reference


class Loan(models.Model):

    name = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=11, null=True)
    nid = models.CharField(max_length=17, null=True)
    amount = models.CharField(max_length=5, null=True)
    join_date = models.DateField(null=True)
    reference = models.ForeignKey(Reference, null=True, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=10, null=True, default=1)

    def __str__(self):
        return self.name

reference/models.py
from django.db import models
# from savings.models import Savings


class Reference(models.Model):
    name = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=11, null=True)
    nid = models.CharField(max_length=17, null=True)
    # savings = models.OneToOneField(Savings, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return str(self.name)

reference/forms.py
from django import forms
from . models import Reference


class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = ['name', 'address', 'mobile', 'nid']

reference/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from loan.models import Loan
from installment.models import LoanInstallment
from . forms import ReferenceForm
from . models import Reference
import datetime


@login_required
def add(request):

    if request.method == 'POST':
        form = ReferenceForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data.get('name')
            messages.success(request, f'Loan created successfully for {name}')
            form.save()
            return redirect('dashboard')

    else:
        form = ReferenceForm()

    context = {
        'form': form
    }

    return render(request, 'reference/add.html', context)


@login_required
def list(request):

    reference = Reference.objects.all()

    return render(request, 'reference/list.html', {'references': reference})


@login_required
def profile(request, id):

    reference = Reference.objects.get(id=id)

    due = []

    ls = Loan.objects.filter(reference=id)

    for l in ls:
        current_week = datetime.datetime.utcnow().isocalendar()[1]
        start_week = datetime.date(l.join_date.year, l.join_date.month, l.join_date.day).isocalendar()[1]

        if current_week > 33:
            current_week -= 33
            start_week -= 33
        else:
            current_week += 19
            start_week += 19

        k = LoanInstallment.objects.filter(name=l.id)
        week_passed = current_week - start_week
        loan_paid = k.count()
        l.overdue = week_passed - k.count()
        l.loan_paid = loan_paid
        l.current_week = current_week
        l.start_week = start_week

        due.append(l)

    context = {
        'title': 'Reference Profile',
        'reference': reference,
        'loans': due,
    }

    return render(request, 'reference/profile.html', context)

templates/reference/add.html
{% extends '../master.html' %}
{% load crispy_forms_tags %}

    {% block content %}

        <section class="content-header">
          <h1>
            Add New Reference:
          </h1>
        </section>

        <section class="content">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Information Form</h3>
                </div>

                <form method="POST">
                    {% csrf_token %}

                    {{form|crispy}}

                    <button type="submit" class="btn btn-success pull-right">Join Him</button>
                </form>

                <!-- <form class="form-horizontal">
                  <div class="box-body">
                    <div class="form-group">
                      <label class="col-sm-3 control-label">Name</label>

                      <div class="col-sm-9">
                        <input type="text" class="form-control" placeholder="Full Name">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-sm-3 control-label">Address</label>

                      <div class="col-sm-9">
                        <input type="text" class="form-control" placeholder="Permanent Address">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-sm-3 control-label">Mobile No</label>

                      <div class="col-sm-9">
                        <input type="number" class="form-control" placeholder="Mobile Number">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-sm-3 control-label">NID No</label>

                      <div class="col-sm-9">
                        <input type="number" class="form-control" placeholder="NID Number">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-sm-3 control-label">Saving Amount</label>

                      <div class="col-sm-9">
                        <input type="number" class="form-control" placeholder="Weekly Savings Amount">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-sm-3 control-label">Joining Date</label>

                      <div class="col-sm-9">
                        <input type="date" class="form-control" placeholder="Joining Date">
                      </div>
                    </div>
                  </div>

                  <div class="box-footer">
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <button type="submit" class="btn btn-success pull-right">Join Him</button>
                  </div>
                </form> -->
              </div>
            </div>
          </div>
        </section>

    {% endblock %}

templates/reference/list.html
{% extends '../master.html' %}

    {% block content %}

      <section class="content-header">
        <h1>
            Reference:
        </h1>
      </section>

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-body">
                <table id="datatable" class="table table-bordered table-striped">
                  <thead>
                      <tr>
                        <th>Sl No.</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Mobile No</th>
                        <th>NID No</th>
                        <th>Loan Refference</th>
                        <th>Status</th>
                      </tr>
                  </thead>
                  <tbody>

                    {% for reference in references %}
                      <tr>
                        <td>{{ reference.id }}</td>
                        <td>
                          {% if reference.savings.name %}
                            {{ reference.savings.name }}
                          {% else %}
                            {{ reference.name }}
                          {% endif %}
                        </td>
                        <td>
                          {% if reference.savings.address %}
                            {{ reference.savings.address }}
                          {% else %}
                            {{ reference.address }}
                          {% endif %}
                        </td>
                        <td>
                          {% if reference.savings.mobile %}
                            {{ reference.savings.mobile }}
                          {% else %}
                            {{ reference.mobile }}
                          {% endif %}
                        </td>
                        <td>
                          {% if reference.savings.nid %}
                            {{ reference.savings.nid }}
                          {% else %}
                            {{ reference.address }}
                          {% endif %}
                        </td>
                        <td>
                          {{ reference.loan_set.count }}
                        </td>
                        <td>
                            <a href="{% url 'reference_profile' reference.id %}" class="btn btn-default">
                                View Details
                            </a>
                        </td>
                      </tr>
                    {% endfor %}

                  </tbody>

                  <tfoot>
                    <tr>
                      <th>Sl No.</th>
                      <th>Name</th>
                      <th>Address</th>
                      <th>Mobile No</th>
                      <th>NID No</th>
                      <th>Loan Refference</th>
                      <th>Status</th>
                    </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>

  {% endblock %}

templates/reference/profile.html
{% extends '../master.html' %}
{% load mathfilters %}
{% load staticfiles %}

    {% block content %}

        <section class="content-header">
          <h1>
            {{ reference.name }}'s Profile:
          </h1>
        </section>

        <section class="content">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12 text-center">
              <div class="box box-info">
                <div class="box-header with-border">
                  <h3 class="box-title">Profile Details</h3>
                </div>

                <table id="user_details" class="table table-bordered table-striped">
                  <tbody>
                      <tr>
                        <th>User No.</th>
                        <td>{{ reference.id }}</td>
                      </tr>
                      <tr>
                        <th>Address</th>
                        <td>{{ reference.address }}</td>
                      </tr>
                      <tr>
                        <th>Mobile No</th>
                        <td>{{ reference.mobile }}</td>
                      </tr>
                      <tr>
                        <th>NID No</th>
                        <td>{{ reference.nid }}</td>
                      </tr>
                      <tr>
                        <th>Loan Reference</th>
                        <td>{{ reference.loan_set.count }}</td>
                      </tr>
                  </tbody>
                </table>
              </div>
            </div>


            <div class="col-lg-6 col-md-6 col-xs-12">
              <div class="box box-widget widget-user-2">
                <div class="widget-user-header bg-green">
                  <h3 class="text-center">Loan Reference List</h3>
                </div>
                <div class="box-footer no-padding">
                  <table id="user_details" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>Name</th>
                          <th>Joining Date</th>
                          <th>Loan Amount</th>
                          <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>

                      {% for loan in loans %}

                        <tr>
                          <td>{{ loan.name }}</td>
                          <td>{{ loan.join_date }}</td>
                          <td>{{ loan.amount }}</td>
                          <td>
                            {% if loan.overdue > 4 %}
                              <span class="label label-danger">Inactive</span>
                            {% elif loan.overdue > 1 %}
                              <span class="label label-warning">Has Due</span>
                            {% elif loan.overdue == 1 %}
                              <span class="label label-primary">Delayed</span>
                            {% else %}
                              <span class="label label-success">Perfect</span>
                            {% endif %}
                          </td>
                          <td>
                            <a href="{% url 'loan_profile' loan.id %}" class="btn btn-default">
                                View Details
                            </a>
                          </td>
                        </tr>

                      {% endfor %}

                    </tbody>
                    <thead>
                        <tr>
                          <th>Name</th>
                          <th>Joining Date</th>
                          <th>Loan Amount</th>
                          <th>Status</th>
                        </tr>
                    </thead>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </section>

    {% endblock %}